import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/site";

export const dynamic = "force-static";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/dashboard", "/dashboard/", "/staff", "/staff/", "/api", "/api/"],
      },
      {
        userAgent: [
          "GPTBot",
          "ChatGPT-User",
          "ChatGPT Agent",
          "OAI-SearchBot",
          "OAI-AdsBot",
          "Operator",
          "OpenAI",
          "ClaudeBot",
          "Claude-SearchBot",
          "Claude-User",
          "Claude-Web",
          "Claude-Code",
          "anthropic-ai",
          "PerplexityBot",
          "Perplexity-User",
          "Google-Extended",
          "GoogleOther",
          "Google-CloudVertexBot",
          "Google-Agent",
          "GoogleAgent-Mariner",
          "GoogleAgent-URLContext",
          "Gemini-Deep-Research",
          "Google-Gemini-CLI",
          "Google-NotebookLM",
          "NotebookLM",
          "Applebot-Extended",
          "Bytespider",
          "CCBot",
          "meta-externalagent",
          "meta-externalfetcher",
          "Cursor",
          "Amazonbot",
          "cohere-ai",
          "MistralAI-User",
          "MistralAI-Index",
          "MistralAI-Training",
          "DeepSeekBot",
          "KimiBot",
          "Kimi-SearchBot",
          "Kimi-User",
          "QwenBot",
          "DuckAssistBot",
          "YouBot",
          "AI2Bot",
          "Bravebot",
          "kagi-fetcher",
          "PhindBot",
          "TavilyBot",
          "Devin",
          "Manus-User",
          "NovaAct",
          "Trae",
          "opencode",
        ],
        allow: "/",
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
